const BUILD='16'
const W={w:900,h:560,ground:500},DT=1/120,G=900,MAX=120,SCALE=6.25
const c=document.getElementById('game'),x=c.getContext('2d')
let dpr=1,v={s:1,ox:0,oy:0,cw:0,ch:0},acc=0,last=performance.now(),drag=false,pid=null,updating=false,audio=null
let shake=0,flash=0,trail=[],dust=[],phase='READY',phaseTime=0,score=0
const anchor={x:155,y:390},weak={x:665,y:445,w:24,h:110},support={x:790,y:445,w:24,h:110},beam={x:728,y:378,w:170,h:24,angle:0,y:378},monster={x:735,y:464,state:'IDLE'}
let ball
const updateBtn={x:777,y:18,w:103,h:38},restartBtn={x:780,y:514,w:100,h:30}
function reset(){ball={x:anchor.x,y:anchor.y,vx:0,vy:0,r:20,flying:false};drag=false;trail=[];dust=[];phase='READY';phaseTime=0;score=0;shake=0;flash=0;beam.angle=0;beam.y=378;monster.state='IDLE'}
function resize(){dpr=Math.min(devicePixelRatio||1,2);v.cw=innerWidth;v.ch=innerHeight;c.width=v.cw*dpr;c.height=v.ch*dpr;c.style.width=v.cw+'px';c.style.height=v.ch+'px';v.s=Math.min(v.cw/W.w,v.ch/W.h);v.ox=(v.cw-W.w*v.s)/2;v.oy=(v.ch-W.h*v.s)/2}
function pos(e){return{x:(e.clientX-v.ox)/v.s,y:(e.clientY-v.oy)/v.s}}
function inside(p,r){return p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h}
c.addEventListener('pointerdown',e=>{const p=pos(e);if(inside(p,updateBtn)){forceUpdate();return}if(inside(p,restartBtn)){reset();return}if(phase==='DONE'){reset();return}if(ball.flying||phase!=='READY')return;if(Math.hypot(p.x-ball.x,p.y-ball.y)<=60){drag=true;pid=e.pointerId;c.setPointerCapture?.(pid);e.preventDefault()}},{passive:false})
c.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==pid)return;const p=pos(e),dx=p.x-anchor.x,dy=p.y-anchor.y,d=Math.hypot(dx,dy)||1,q=Math.min(MAX,d);ball.x=anchor.x+dx/d*q;ball.y=anchor.y+dy/d*q;e.preventDefault()},{passive:false})
function release(e){if(!drag||e.pointerId!==pid)return;drag=false;pid=null;const dx=anchor.x-ball.x,dy=anchor.y-ball.y;if(Math.hypot(dx,dy)<8){ball.x=anchor.x;ball.y=anchor.y;return}ball.vx=dx*SCALE;ball.vy=dy*SCALE;ball.flying=true;tone(180,.045);e.preventDefault()}
c.addEventListener('pointerup',release,{passive:false});c.addEventListener('pointercancel',release,{passive:false});addEventListener('resize',resize)
function flightStep(s,dt=DT){s.vy+=G*dt;s.x+=s.vx*dt;s.y+=s.vy*dt;return s}
function trajectory(){const s={x:ball.x,y:ball.y,vx:(anchor.x-ball.x)*SCALE,vy:(anchor.y-ball.y)*SCALE},a=[];for(let i=1;i<=160;i++){flightStep(s);if(i%10===0)a.push({x:s.x,y:s.y});if(a.length>=14||s.y>=W.ground)break}return a}
function tone(f,d){try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(_){}}
function hitWeak(){phase='CRACK';phaseTime=0;monster.state='ALARMED';ball.flying=false;shake=7;flash=.5;tone(110,.08);try{navigator.vibrate?.(25)}catch(_){};for(let i=0;i<14;i++)dust.push({x:weak.x,y:weak.y-20,vx:(Math.random()-.5)*90,vy:-Math.random()*90,a:1})}
function step(){shake=Math.max(0,shake-DT*25);flash=Math.max(0,flash-DT*3);for(const d of dust){d.x+=d.vx*DT;d.y+=d.vy*DT;d.vy+=250*DT;d.a-=DT*1.5}dust=dust.filter(d=>d.a>0)
 if(ball.flying){trail.push({x:ball.x,y:ball.y,a:1});if(trail.length>18)trail.shift();for(const t of trail)t.a*=.93;flightStep(ball)
 const hx=Math.max(weak.x-weak.w/2,Math.min(ball.x,weak.x+weak.w/2)),hy=Math.max(weak.y-weak.h/2,Math.min(ball.y,weak.y+weak.h/2));if((ball.x-hx)**2+(ball.y-hy)**2<=ball.r**2){hitWeak();return}
 if(ball.y+ball.r>=W.ground){ball.y=W.ground-ball.r;ball.flying=false;phase='MISS';phaseTime=0}if(ball.x>W.w+60){ball.flying=false;phase='MISS';phaseTime=0}}
 if(phase==='CRACK'||phase==='COLLAPSE'||phase==='MISS'){phaseTime+=DT}
 if(phase==='CRACK'&&phaseTime>.24){phase='COLLAPSE';phaseTime=0;tone(70,.18)}
 if(phase==='COLLAPSE'){beam.angle=Math.min(.48,beam.angle+DT*1.65);beam.y=Math.min(428,beam.y+DT*88);if(phaseTime>.42&&monster.state!=='DEFEATED'){monster.state='DEFEATED';score=1000;shake=12;flash=1;tone(55,.22);try{navigator.vibrate?.([25,30,55])}catch(_){}}if(phaseTime>.9)phase='DONE'}
 if(phase==='MISS'&&phaseTime>.65){ball={x:anchor.x,y:anchor.y,vx:0,vy:0,r:20,flying:false};trail=[];phase='READY'}
}
function rr(a,b,w,h,r,f){x.beginPath();x.roundRect(a,b,w,h,r);x.fillStyle=f;x.fill()}
function critter(){x.save();x.translate(ball.x,ball.y);let sx=1,sy=1;if(drag){const p=Math.min(1,Math.hypot(anchor.x-ball.x,anchor.y-ball.y)/MAX);sx=1+.18*p;sy=1-.12*p}else if(ball.flying){sx=1.13;sy=.9}x.scale(sx,sy);x.fillStyle='#ef5b45';x.beginPath();x.arc(0,0,20,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.beginPath();x.arc(-7,-6,6,0,Math.PI*2);x.arc(7,-6,6,0,Math.PI*2);x.fill();x.fillStyle='#17202b';x.beginPath();x.arc(-6,-5,2.5,0,Math.PI*2);x.arc(8,-5,2.5,0,Math.PI*2);x.fill();x.strokeStyle='#7c241d';x.lineWidth=2.5;x.beginPath();if(ball.flying)x.arc(0,6,5,0,Math.PI*2);else{x.moveTo(-5,7);x.lineTo(5,7)}x.stroke();x.restore()}
function monsterDraw(){x.save();x.translate(monster.x,monster.y);if(monster.state==='DEFEATED'){x.rotate(-.7);x.scale(1.15,.7)}x.fillStyle='#8256cf';x.beginPath();x.ellipse(0,0,25,24,0,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.beginPath();x.arc(-8,-6,6,0,Math.PI*2);x.arc(8,-6,6,0,Math.PI*2);x.fill();x.fillStyle='#222';x.beginPath();x.arc(-7,-5,2.5,0,Math.PI*2);x.arc(9,-5,2.5,0,Math.PI*2);x.fill();x.strokeStyle='#432b70';x.lineWidth=3;x.beginPath();if(monster.state==='ALARMED')x.arc(0,7,6,0,Math.PI*2);else if(monster.state==='DEFEATED'){x.moveTo(-8,7);x.lineTo(8,7)}else x.arc(0,4,9,0,Math.PI);x.stroke();x.restore()}
function block(b,weakOne=false){x.fillStyle=weakOne?'#d69449':'#b97836';x.strokeStyle='#75451f';x.lineWidth=3;x.fillRect(b.x-b.w/2,b.y-b.h/2,b.w,b.h);x.strokeRect(b.x-b.w/2,b.y-b.h/2,b.w,b.h);if(weakOne&&phase==='READY'){x.strokeStyle='#5b3217';x.beginPath();x.moveTo(b.x-4,b.y-26);x.lineTo(b.x+5,b.y-12);x.lineTo(b.x-5,b.y+3);x.lineTo(b.x+6,b.y+21);x.stroke()}}
function world(){const g=x.createLinearGradient(0,0,0,W.h);g.addColorStop(0,'#72c9ff');g.addColorStop(1,'#d9f2ff');x.fillStyle=g;x.fillRect(0,0,W.w,W.h);x.fillStyle='#8ecf65';x.beginPath();x.moveTo(0,430);x.quadraticCurveTo(180,350,360,430);x.quadraticCurveTo(590,345,900,425);x.lineTo(900,500);x.lineTo(0,500);x.fill();x.fillStyle='#6fb84f';x.fillRect(0,W.ground,W.w,60);x.fillStyle='#4b8d37';x.fillRect(0,W.ground,W.w,8)
 rr(14,14,872,58,18,'#101827dd');x.textBaseline='middle';x.fillStyle='#fff';x.font='900 23px system-ui';x.textAlign='left';x.fillText('CRITTER CRASH',32,43);x.font='800 13px system-ui';x.fillStyle='#cbd5e1';x.fillText('FIRST CRASH',222,43);x.textAlign='right';x.fillStyle='#fff';x.fillText('SCORE '+score,758,43);rr(updateBtn.x,updateBtn.y,updateBtn.w,updateBtn.h,12,'#f6b73c');x.fillStyle='#251600';x.font='900 12px system-ui';x.textAlign='center';x.fillText(updating?'UPDATING…':'↻ UPDATE',828,38)
 x.strokeStyle='#75451f';x.lineWidth=16;x.lineCap='round';x.beginPath();x.moveTo(anchor.x-25,W.ground);x.lineTo(anchor.x-10,anchor.y-8);x.moveTo(anchor.x+25,W.ground);x.lineTo(anchor.x+10,anchor.y-8);x.stroke()
 if(drag){x.strokeStyle='#3a2518';x.lineWidth=7;x.beginPath();x.moveTo(anchor.x-10,anchor.y-8);x.lineTo(ball.x,ball.y);x.lineTo(anchor.x+10,anchor.y-8);x.stroke();for(const p of trajectory()){x.fillStyle='#ffffffd5';x.beginPath();x.arc(p.x,p.y,4,0,Math.PI*2);x.fill()}}
 for(const t of trail){x.globalAlpha=t.a*.3;x.fillStyle='#fff';x.beginPath();x.arc(t.x,t.y,7,0,Math.PI*2);x.fill()}x.globalAlpha=1
 if(phase==='READY'||phase==='MISS')block(weak,true);else{x.save();x.translate(weak.x-8,W.ground-7);x.rotate(-1.05);block({x:0,y:0,w:18,h:64},true);x.restore();x.save();x.translate(weak.x+12,W.ground-5);x.rotate(.72);block({x:0,y:0,w:17,h:48},true);x.restore()}block(support);x.save();x.translate(beam.x,beam.y);x.rotate(beam.angle);block({x:0,y:0,w:beam.w,h:beam.h});x.restore();monsterDraw();critter()
 for(const d of dust){x.globalAlpha=d.a;x.fillStyle='#b78455';x.fillRect(d.x-3,d.y-3,6,6)}x.globalAlpha=1
 rr(14,512,872,38,12,'#101827dd');x.fillStyle='#dbe7f5';x.font='700 13px system-ui';x.textAlign='left';x.fillText(phase==='READY'?'Find the weak point • Pull • Aim • Crash':phase==='CRACK'?'CRACK!':phase==='COLLAPSE'?'WATCH IT FALL…':phase==='DONE'?'FIRST CRASH! +1000':'Try another angle',28,531);x.textAlign='right';x.fillStyle='#f6b73c';x.fillText('RESTART',870,531);x.fillStyle='#10182788';x.font='700 10px ui-monospace';x.textAlign='center';x.fillText('BUILD '+BUILD,450,493)
 if(phase==='DONE'){rr(330,90,240,48,18,'#101827dd');x.fillStyle='#fff';x.font='900 18px system-ui';x.fillText('CRASH! +1000',450,114)}
}
function draw(){x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,v.cw,v.ch);x.fillStyle='#101827';x.fillRect(0,0,v.cw,v.ch);x.save();x.translate(v.ox+(Math.random()-.5)*shake,v.oy+(Math.random()-.5)*shake);x.scale(v.s,v.s);world();if(flash){x.globalAlpha=flash*.12;x.fillStyle='#fff';x.fillRect(0,0,W.w,W.h);x.globalAlpha=1}x.restore()}
function frame(now){acc+=Math.min(.05,(now-last)/1000);last=now;while(acc>=DT){step();acc-=DT}draw();requestAnimationFrame(frame)}
async function forceUpdate(){if(updating)return;updating=true;try{if('serviceWorker'in navigator){for(const r of await navigator.serviceWorker.getRegistrations()){try{await r.update()}catch(_){}if(r.waiting)r.waiting.postMessage({type:'SKIP_WAITING'})}}for(const k of await caches.keys())await caches.delete(k);const u=new URL(location.href);u.searchParams.set('_build',BUILD+'-'+Date.now());location.replace(u.href)}catch(_){location.reload()}}
async function sw(){if(!('serviceWorker'in navigator))return;try{const r=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await r.update()}catch(_){}}
resize();reset();sw();requestAnimationFrame(frame)