const BUILD='13'
const W={w:900,h:560,ground:500},DT=1/120,G=900,MAX=120,SCALE=6.25
const c=document.getElementById('game'),x=c.getContext('2d')
let dpr=1,v={s:1,ox:0,oy:0,cw:0,ch:0},acc=0,last=performance.now(),drag=false,pid=null,updating=false
const anchor={x:155,y:390},target={x:720,y:365,r:48}
let ball,hit=false,shots=0
const updateBtn={x:777,y:18,w:103,h:38},resetBtn={x:780,y:514,w:100,h:30}
function resetBall(){ball={x:anchor.x,y:anchor.y,vx:0,vy:0,r:20,flying:false};hit=false}
function resetAll(){shots=0;resetBall()}
function resize(){dpr=Math.min(devicePixelRatio||1,2);v.cw=innerWidth;v.ch=innerHeight;c.width=v.cw*dpr;c.height=v.ch*dpr;c.style.width=v.cw+'px';c.style.height=v.ch+'px';v.s=Math.min(v.cw/W.w,v.ch/W.h);v.ox=(v.cw-W.w*v.s)/2;v.oy=(v.ch-W.h*v.s)/2}
function pos(e){return{x:(e.clientX-v.ox)/v.s,y:(e.clientY-v.oy)/v.s}}
function inside(p,r){return p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h}
c.addEventListener('pointerdown',e=>{const p=pos(e);if(inside(p,updateBtn)){forceUpdate();return}if(inside(p,resetBtn)){resetAll();return}if(ball.flying)return;if(Math.hypot(p.x-ball.x,p.y-ball.y)<=60){drag=true;pid=e.pointerId;c.setPointerCapture?.(pid);e.preventDefault()}},{passive:false})
c.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==pid)return;const p=pos(e),dx=p.x-anchor.x,dy=p.y-anchor.y,d=Math.hypot(dx,dy)||1,pull=Math.min(MAX,d);ball.x=anchor.x+dx/d*pull;ball.y=anchor.y+dy/d*pull;e.preventDefault()},{passive:false})
function release(e){if(!drag||e.pointerId!==pid)return;drag=false;pid=null;const dx=anchor.x-ball.x,dy=anchor.y-ball.y,pull=Math.hypot(dx,dy);if(pull<8){resetBall();return}ball.vx=dx*SCALE;ball.vy=dy*SCALE;ball.flying=true;shots++;e.preventDefault()}
c.addEventListener('pointerup',release,{passive:false});c.addEventListener('pointercancel',release,{passive:false});addEventListener('resize',resize)
function trajectory(){const dx=anchor.x-ball.x,dy=anchor.y-ball.y,vx=dx*SCALE,vy=dy*SCALE,a=[];for(let i=1;i<=14;i++){const t=i*.095;a.push({x:ball.x+vx*t,y:ball.y+vy*t+.5*G*t*t})}return a}
function step(){if(!ball.flying)return;ball.vy+=G*DT;ball.x+=ball.vx*DT;ball.y+=ball.vy*DT;if(!hit&&Math.hypot(ball.x-target.x,ball.y-target.y)<=ball.r+target.r){hit=true;ball.vx*=-.28;ball.vy*=-.28;try{navigator.vibrate?.(25)}catch(_){}}if(ball.y+ball.r>=W.ground){ball.y=W.ground-ball.r;ball.flying=false}if(ball.x>W.w+80||ball.x<-80||ball.y>W.h+80)ball.flying=false}
function rr(a,b,w,h,r,fill){x.beginPath();x.roundRect(a,b,w,h,r);x.fillStyle=fill;x.fill()}
function critter(){x.fillStyle='#ef5b45';x.beginPath();x.arc(ball.x,ball.y,ball.r,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.beginPath();x.arc(ball.x-7,ball.y-6,5,0,Math.PI*2);x.arc(ball.x+7,ball.y-6,5,0,Math.PI*2);x.fill();x.fillStyle='#17202b';x.beginPath();x.arc(ball.x-6,ball.y-5,2,0,Math.PI*2);x.arc(ball.x+8,ball.y-5,2,0,Math.PI*2);x.fill()}
function world(){const g=x.createLinearGradient(0,0,0,W.h);g.addColorStop(0,'#72c9ff');g.addColorStop(1,'#d9f2ff');x.fillStyle=g;x.fillRect(0,0,W.w,W.h);x.fillStyle='#6fb84f';x.fillRect(0,W.ground,W.w,60);x.fillStyle='#4b8d37';x.fillRect(0,W.ground,W.w,8);rr(14,14,872,58,18,'#101827dd');x.textBaseline='middle';x.fillStyle='#fff';x.font='900 23px system-ui';x.textAlign='left';x.fillText('CRITTER CRASH — SHOOTING LAB',32,43);rr(updateBtn.x,updateBtn.y,updateBtn.w,updateBtn.h,12,'#f6b73c');x.fillStyle='#251600';x.font='900 12px system-ui';x.textAlign='center';x.fillText(updating?'UPDATING…':'↻ UPDATE',828,38);x.strokeStyle='#75451f';x.lineWidth=16;x.lineCap='round';x.beginPath();x.moveTo(anchor.x-25,W.ground);x.lineTo(anchor.x-10,anchor.y-8);x.moveTo(anchor.x+25,W.ground);x.lineTo(anchor.x+10,anchor.y-8);x.stroke();if(drag){x.strokeStyle='#3a2518';x.lineWidth=7;x.beginPath();x.moveTo(anchor.x-10,anchor.y-8);x.lineTo(ball.x,ball.y);x.lineTo(anchor.x+10,anchor.y-8);x.stroke();for(const p of trajectory()){x.fillStyle='#ffffffd5';x.beginPath();x.arc(p.x,p.y,4,0,Math.PI*2);x.fill()}}x.fillStyle=hit?'#43b66b':'#754bd1';x.beginPath();x.arc(target.x,target.y,target.r,0,Math.PI*2);x.fill();x.strokeStyle='#fff';x.lineWidth=4;x.stroke();x.fillStyle='#fff';x.font='900 16px system-ui';x.textAlign='center';x.fillText(hit?'HIT':'TARGET',target.x,target.y);critter();rr(14,512,872,38,12,'#101827dd');x.fillStyle='#dbe7f5';x.font='700 13px system-ui';x.textAlign='left';x.fillText('BUILD '+BUILD+' • GATE 1 • '+(v.cw>=v.ch?'LANDSCAPE':'PORTRAIT')+' • SHOTS '+shots,28,531);x.textAlign='right';x.fillStyle='#f6b73c';x.fillText('RESET',870,531);if(!ball.flying&&!drag&&shots>0){rr(300,92,300,44,18,'#101827dd');x.fillStyle='#fff';x.font='800 15px system-ui';x.textAlign='center';x.fillText(hit?'Collision confirmed — tap RESET':'Shot complete — tap RESET',450,114)}if(drag){rr(335,82,230,38,16,'#101827cc');x.fillStyle='#fff';x.font='800 14px system-ui';x.textAlign='center';x.fillText('PULL '+Math.round(Math.hypot(anchor.x-ball.x,anchor.y-ball.y))+' / '+MAX,450,101)}}
function draw(){x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,v.cw,v.ch);x.fillStyle='#101827';x.fillRect(0,0,v.cw,v.ch);x.save();x.translate(v.ox,v.oy);x.scale(v.s,v.s);world();x.restore()}
function frame(now){acc+=Math.min(.05,(now-last)/1000);last=now;while(acc>=DT){step();acc-=DT}draw();requestAnimationFrame(frame)}
async function forceUpdate(){if(updating)return;updating=true;try{if('serviceWorker'in navigator){for(const r of await navigator.serviceWorker.getRegistrations()){try{await r.update()}catch(_){}if(r.waiting)r.waiting.postMessage({type:'SKIP_WAITING'})}}for(const k of await caches.keys())await caches.delete(k);const u=new URL(location.href);u.searchParams.set('_build',BUILD+'-'+Date.now());location.replace(u.href)}catch(_){location.reload()}}
async function sw(){if(!('serviceWorker'in navigator))return;try{const r=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await r.update()}catch(_){}}
resize();resetAll();sw();requestAnimationFrame(frame)